# Generated by Django 4.1.3 on 2023-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="field_name",
            field=models.FileField(default="", max_length=254, upload_to="post_files/"),
            preserve_default=False,
        ),
    ]
